HOST     = '212.8.247.94'
PORT     = 5432
DATABASE = 'home'
USER     = 'student'
PASSWORD = 'qwerty'

STG_PASSPORT_BLACKLIST      = '"p3"."ENV_STG_PASSPORT_BLACKLIST"'
STG_TERMINALS               = '"p3"."ENV_STG_TERMINALS"'
STG_TRANSACTIONS            = '"p3"."ENV_STG_TRANSACTIONS"'

STG_DEL_PASSPORT_BLACKLIST  = '"p3"."ENV_STG_DEL_PASSPORT_BLACKLIST"'
STG_DEL_TERMINALS           = '"p3"."ENV_STG_DEL_TERMINALS"'
STG_DEL_TRANSACTIONS        = '"p3"."ENV_STG_DEL_TRANSACTIONS"'

STG_ACCOUNTS                = '"p3"."ENV_STG_ACCOUNTS"'
STG_CARDS                   = '"p3"."ENV_STG_CARDS"'
STG_CLIENTS                 = '"p3"."ENV_STG_CLIENTS"'

STG_DEL_ACCOUNTS            = '"p3"."ENV_STG_DEL_ACCOUNTS"'
STG_DEL_CARDS               = '"p3"."ENV_STG_DEL_CARDS"'
STG_DEL_CLIENTS             = '"p3"."ENV_STG_DEL_CLIENTS"'

DWH_DIM_ACCOUNTS_HIST       = '"p3"."ENV_DWH_DIM_ACCOUNTS_HIST"'
DWH_DIM_CARDS_HIST          = '"p3"."ENV_DWH_DIM_CARDS_HIST"'
DWH_DIM_TERMINALS_HIST      = '"p3"."ENV_DWH_DIM_TERMINALS_HIST"'
DWH_DIM_CLIENTS_HIST        = '"p3"."ENV_DWH_DIM_CLIENTS_HIST"'

DWH_FACT_TRANSACTIONS       = '"p3"."ENV_DWH_FACT_TRANSACTIONS"'
DWH_FACT_PASSPORT_BLACKLIST = '"p3"."ENV_DWH_FACT_PASSPORT_BLACKLIST"'

ENV_META                    = '"p3"."ENV_META"'
ENV_REP_FRAUD               = '"p3"."ENV_REP_FRAUD"'     