HOST     = '212.8.247.94'
PORT     = 5432
DATABASE = 'home'
USER     = 'student'
PASSWORD = 'qwerty'

PASSPORT_BLACKLIST = '"p3"."ENV_DWH_FACT_PASSPORT_BLACKLIST"'
TERMINALS          = '"p3"."ENV_DWH_FACT_TERMINALS"'
TRANSACTIONS       = '"p3"."ENV_DWH_FACT_TRANSACTIONS"'