HOST     = '212.8.247.94'
PORT     = 5432
DATABASE = 'home'
USER     = 'student'
PASSWORD = 'qwerty'

STG_PASSPORT_BLACKLIST      = '"p3"."ENV_STG_PASSPORT_BLACKLIST"'
STG_TERMINALS               = '"p3"."ENV_STG_TERMINALS"'
STG_TRANSACTIONS            = '"p3"."ENV_STG_TRANSACTIONS"'

STG_PASSPORT_BLACKLIST_DEL  = '"p3"."ENV_STG_PASSPORT_BLACKLIST_DEL"'
STG_TERMINALS_DEL           = '"p3"."ENV_STG_TERMINALS_DEL"'
STG_TRANSACTIONS_DEL        = '"p3"."ENV_STG_TRANSACTIONS_DEL"'

STG_ACCOUNTS_DEL            = '"p3"."ENV_STG_ACCOUNTS_DEL"'
STG_CARDS_DEL               = '"p3"."ENV_STG_CARDS_DEL"'
STG_CLIENTS_DEL             = '"p3"."ENV_STG_CLIENTS_DEL"'

STG_ACCOUNTS_DEL            = '"p3"."ENV_STG_ACCOUNTS_DEL"'
STG_CARDS_DEL               = '"p3"."ENV_STG_CARDS_DEL"'
STG_CLIENTS_DEL             = '"p3"."ENV_STG_CLIENTS_DEL"'

DWH_DIM_ACCOUNTS_HIST       = '"p3"."ENV_DWH_DIM_ACCOUNTS_HIST"'
DWH_DIM_CARDS_HIST          = '"p3"."ENV_DWH_DIM_CARDS_HIST"'
DWH_DIM_TERMINALS_HIST      = '"p3"."ENV_DWH_DIM_TERMINALS_HIST"'
DWH_DIM_CLIENTS_HIST        = '"p3"."ENV_DWH_DIM_CLIENTS_HIST"'

DWH_FACT_TRANSACTIONS       = '"p3"."ENV_DWH_FACT_TRANSACTIONS"'
DWH_FACT_PASSPORT_BLACKLIST = '"p3"."ENV_DWH_FACT_PASSPORT_BLACKLIST"'

ENV_META                    = '"p3"."ENV_META"'
ENV_REP_FRAUD               = '"p3"."ENV_REP_FRAUD"'     