DROP TABLE IF EXISTS "p3"."ENV_STG_PASSPORT_BLACKLIST";
CREATE TABLE "p3"."ENV_STG_PASSPORT_BLACKLIST" (
    "passport_num" varchar(255) NOT NULL,
    "entry_dt" DATE NOT NULL
);

DROP TABLE IF EXISTS "p3"."ENV_STG_TERMINALS";
CREATE TABLE "p3"."ENV_STG_TERMINALS" (
    "terminal_id" varchar(255) NOT NULL,
    "terminal_type" varchar(255) NOT NULL,
    "terminal_city" varchar(255) NOT NULL,
    "terminal_address" varchar(255) NOT NULL
);

DROP TABLE IF EXISTS "p3"."ENV_STG_TRANSACTIONS";
CREATE TABLE "p3"."ENV_STG_TRANSACTIONS" (
    "trans_id" varchar(255) NOT NULL,
    "trans_date" DATE NOT NULL,
    "card_num" varchar(255) NOT NULL,
    "oper_type" varchar(255) NOT NULL,
    "amt" DECIMAL NOT NULL,
    "oper_result" varchar(255) NOT NULL,
    "terminal" varchar(255) NOT NULL
);


DROP TABLE IF EXISTS "p3"."ENV_STG_DEL_PASSPORT_BLACKLIST";
CREATE TABLE "p3"."ENV_STG_DEL_PASSPORT_BLACKLIST" ("passpor_num" varchar(255) NOT NULL);

DROP TABLE IF EXISTS "p3"."ENV_STG_DEL_TERMINALS";
CREATE TABLE "p3"."ENV_STG_DEL_TERMINALS" ("terminal_id" varchar(255) NOT NULL);

DROP TABLE IF EXISTS "p3"."ENV_STG_DEL_TRANSACTIONS";
CREATE TABLE "p3"."ENV_STG_DEL_TRANSACTIONS" ("transaction_id" varchar(255) NOT NULL);



DROP TABLE IF EXISTS "p3"."ENV_STG_ACCOUNTS";
CREATE TABLE "p3"."ENV_STG_ACCOUNTS" AS SELECT * FROM bank.accounts;

DROP TABLE IF EXISTS "p3"."ENV_STG_CARDS";
CREATE TABLE "p3"."ENV_STG_CARDS" AS SELECT * FROM bank.cards;

DROP TABLE IF EXISTS "p3"."ENV_STG_CLIENTS";
CREATE TABLE "p3"."ENV_STG_CLIENTS" AS SELECT * FROM bank.clients;


DROP TABLE IF EXISTS "p3"."ENV_STG_DEL_ACCOUNTS";
CREATE TABLE "p3"."ENV_STG_DEL_ACCOUNTS" ("account_id" varchar(255) NOT NULL);

DROP TABLE IF EXISTS "p3"."ENV_STG_DEL_CARDS";
CREATE TABLE "p3"."ENV_STG_DEL_CARDS" ("card_num" varchar(255) NOT NULL);

DROP TABLE IF EXISTS "p3"."ENV_STG_DEL_CLIENTS";
CREATE TABLE "p3"."ENV_STG_DEL_CLIENTS" ("client_id" varchar(255) NOT NULL);